### ISSUE TITLE
Now / docker compatibility ? 

### ISSUE THREAD

**Issue by alechp** [CaptainChemist/blog-prisma2#16]
## Error

Project works great when running docker compose locally. Seems to fall apart when on `now dev` or now.sh

```
message: 'Network error: request to http://backend:4000/graphql failed, reason: getaddrinfo ENOTFOUND backend backend:4000',
```

## Comment
I recall having to work around similar issues when I was building https://github.com/servexyz/prisma-starter (for v1) 

I assume that it's possible to publish prisma to now v2 since they said they were working with the Prisma team to make this possible.

However, I'm not sure if docker is supported any longer. I'm considering checking out: https://cloud.google.com/run/

## Question
How did you get now working with docker compose?

### Running on now.sh platform
[image:C2467A59-A263-4253-A12E-26596E172BA9-11188-000010D830978842/Screen Shot 2019-10-24 at 11.11.02 AM.png]
```sh
START RequestId: 1835e42b-5afa-4f9b-a3ad-f9a08e757e74 Version: $LATEST
2019-10-24T18:10:54.526Z	1835e42b-5afa-4f9b-a3ad-f9a08e757e74	Error while running `getDataFromTree` { Error: Network error: request to http://backend:4000/graphql failed, reason: getaddrinfo ENOTFOUND backend backend:4000
    at new ApolloError (/var/task/frontend/node_modules/apollo-client/bundle.umd.js:92:26)
    at /var/task/frontend/node_modules/apollo-client/bundle.umd.js:1581:34
    at /var/task/frontend/node_modules/apollo-client/bundle.umd.js:2001:15
    at Set.forEach (<anonymous>)
    at /var/task/frontend/node_modules/apollo-client/bundle.umd.js:1999:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/var/task/frontend/node_modules/apollo-client/bundle.umd.js:1997:20)
    at /var/task/frontend/node_modules/apollo-client/bundle.umd.js:1476:29
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  graphQLErrors: [],
  networkError: 
   { FetchError: request to http://backend:4000/graphql failed, reason: getaddrinfo ENOTFOUND backend backend:4000
    at ClientRequest.<anonymous> (/var/task/frontend/node_modules/node-fetch/lib/index.js:1455:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:355:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
     message: 'request to http://backend:4000/graphql failed, reason: getaddrinfo ENOTFOUND backend backend:4000',
     type: 'system',
     errno: 'ENOTFOUND',
     code: 'ENOTFOUND' },
  message: 'Network error: request to http://backend:4000/graphql failed, reason: getaddrinfo ENOTFOUND backend backend:4000',
  extraInfo: undefined }
END RequestId: 1835e42b-5afa-4f9b-a3ad-f9a08e757e74
REPORT RequestId: 1835e42b-5afa-4f9b-a3ad-f9a08e757e74	Duration: 116.39 ms	Billed Duration: 200 ms	Memory Size: 3008 MB	Max Memory Used: 120 MB	Init Duration: 963.08 ms	

```
### Running via `now dev`
```sh
~/Code/alechp/sandbox/prisma/2v/blog-prisma2 prisma-blog*
❯ now dev
> Now CLI 16.4.0 dev (beta) — https://zeit.co/feedback/dev
> Creating initial build
> Using "webpackDevMiddleware" config function defined in next.config.js.
[ info ]  bundled successfully, waiting for typecheck results ...
[ ready ] compiled successfully
[ wait ]  compiling ...
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

> Success! Build completed
> NOTE: Requested port 3000 is already in use
> Ready! Available at http://localhost:3001
[ info ]  bundled successfully, waiting for typecheck results ...
[ ready ] compiled successfully
[ event ] build page: /
[ wait ]  compiling ...
[ info ]  bundled successfully, waiting for typecheck results ...
[ ready ] compiled successfully
Error while running `getDataFromTree` ApolloError: Network error: request to http://backend:4000/graphql failed, reason: getaddrinfo ENOTFOUND backend
    at new ApolloError (/Users/alechp/Code/alechp/.repositories/sandbox/prisma/2v/blog-prisma2/frontend/node_modules/apollo-client/bundle.umd.js:92:26)
    at /Users/alechp/Code/alechp/.repositories/sandbox/prisma/2v/blog-prisma2/frontend/node_modules/apollo-client/bundle.umd.js:1581:34
    at /Users/alechp/Code/alechp/.repositories/sandbox/prisma/2v/blog-prisma2/frontend/node_modules/apollo-client/bundle.umd.js:2001:15
    at Set.forEach (<anonymous>)
    at /Users/alechp/Code/alechp/.repositories/sandbox/prisma/2v/blog-prisma2/frontend/node_modules/apollo-client/bundle.umd.js:1999:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/Users/alechp/Code/alechp/.repositories/sandbox/prisma/2v/blog-prisma2/frontend/node_modules/apollo-client/bundle.umd.js:1997:20)
    at /Users/alechp/Code/alechp/.repositories/sandbox/prisma/2v/blog-prisma2/frontend/node_modules/apollo-client/bundle.umd.js:1476:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  graphQLErrors: [],
  networkError: FetchError: request to http://backend:4000/graphql failed, reason: getaddrinfo ENOTFOUND backend
      at ClientRequest.<anonymous> (/Users/alechp/Code/alechp/.repositories/sandbox/prisma/2v/blog-prisma2/frontend/node_modules/node-fetch/lib/index.js:1455:11)
      at ClientRequest.emit (events.js:210:5)
      at Socket.socketErrorListener (_http_client.js:406:9)
      at Socket.emit (events.js:210:5)
      at emitErrorNT (internal/streams/destroy.js:92:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    message: 'request to http://backend:4000/graphql failed, reason: getaddrinfo ENOTFOUND backend',
    type: 'system',
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND'
  },
  message: 'Network error: request to http://backend:4000/graphql failed, reason: getaddrinfo ENOTFOUND backend',
  extraInfo: undefined
}
```

**Comment by alechp** [comment]
Also, I realize now/docker compatibility is inherently a Zeit issue / not an "issue" for this project. The reason I'm posting this here is because it seems you have figured out a way to get this to work on now.sh and I'd like to understand

**Comment by CaptainChemist** [comment]
Sorry for the delay @alechp - the problem is with line 14 of the `init-apollo.js` file. It seems like isDocker and isBrowser are both coming back to true which is causing it to look at that localhost uri. This points to the BACKEND_URL being incorrect- you will need to update that to the url of the backend server when you deploy it to now.sh. If you instead want to deploy the docker cluster to an ec2 instance or some sort of computer in the cloud- you'd want to instead use the external ip address of that server.

**Comment by image72** [comment]
why not use internal bridge networks?
https://github.com/Joao-Henrique/Docker_Medium_Tutorial/blob/master/docker-compose.yml

**Comment by alechp** [comment]
Didn’t read your tutorial. Am I missing something ?

Alec Hale-Pletka

**Comment by image72** [comment]
dont't care, just off topic idea.
